### Declarative Subscription
@senderUrl=http://localhost:5231
### Send generated
POST {{senderUrl}}/send
Content-Type: application/json

{
    "id": "{{$guid}}",
    "timeStamp": "{{$datetime iso8601}}",
    "type": "1"
}

### Send static
POST {{senderUrl}}/send
Content-Type: application/json

{
  "id": "e9cdd036-c529-4bf9-bd59-d7148ef9237d",
  "timeStamp": "2025-09-26T02:52:04.835Z",
  "type": "1"
}

### Send as Bytes generated
POST {{senderUrl}}/sendasbytes
Content-Type: application/json

{
    "id": "{{$guid}}",
    "timeStamp": "{{$datetime iso8601}}",
    "type": "1"
}

### Send as Bytes static
POST {{senderUrl}}/sendasbytes
Content-Type: application/json

{
  "id": "c6699d32-727b-4e2d-8eaf-9047f461cd34",
  "timeStamp": "2025-09-26T02:56:00.515Z",
  "type": "1"
}