apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprConfig
spec:
  tracing:
    samplingRate: "1"
    stdout: true
    zipkin:
      endpointAddress: "http://localhost:9411/api/v2/spans"
  metrics:
    enabled: true
    http:
      increasedCardinality: true
      pathMatching:
        - /send
        - /sendasbytes
      excludeVerbs: false
    recordErrorCodes: true
    rules:
      - name: dapr_runtime_service_invocation_req_send
        labels:
          - name: method
            regex:
              "send/": "send/.+"
      - name: dapr_runtime_service_invocation_req_sendasbytes
        labels:
          - name: method
            regex:
              "sendasbytes/": "sendasbytes/.+"
    workflow:
      maxConcurrentWorkflowInvocations: 100
      maxConcurrentActivityInvocations: 1000