apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: orderpubsub-kafka
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: brokers
      value: "localhost:9092"
    - name: consumerGroup
      value: "order-group"  # Changed for clarity
    - name: authType
      value: "none"
    - name: authRequired
      value: "false"
    - name: clientID
      value: "dapr-pubsub-client"  # Changed to be more generic
    - name: disableTls
      value: "true"
scopes:
  - producer
  - consumer